import { Tab } from "@/src/components/organisms";
import { Divider, Icons } from "@/src/components/atoms";
import {
  ImagesBlock,
  IconButton,
  PrimaryBtn,
} from "@/src/components/moleculs/";
import { ICard } from "@/src/types/Card";

type Props = {
  card: ICard;
};

const TripLong: React.FC<Props> = ({ card }) => {
  const descriptions = {
    description: card.description,
    "why this place?": card.whyThisPlace.join(' '),
    map: card.mapLink,
  };

  return (
    <article
      className="flex flex-col gap-2
      justify-between items-center"
    >
      <h1 className="w-full text-3xl font-semibold">{card.name}</h1>

      <div className="gap-2 w-full mt-1 grid grid-cols-12">
        <div className="w-full col-span-5">
          <div className="flex gap-2 items-center justify-start">
            <Icons.location />
            <h1 className="text-2xl font-normal">{card.whereIs}</h1>
          </div>

          <div className="mt-6 overflow-scroll max-h-[550px]">
            <Tab descriptions={descriptions} />
          </div>

          <PrimaryBtn text="Save" onClick={() => {}} classes="mt-6" />
        </div>

        <div className="w-full h-full col-span-7">
          <div className="flex gap-4 w-full justify-end h-8">
            <IconButton
              icon={<Icons.heart />}
              text={card.likes.toString()}
              classes=""
            />

            <Divider classes="w-px h-full bg-gray30" />

            <IconButton
              icon={<Icons.user />}
              text={
                card.author === "AI" ? "Generated by AI" : `by ${card.author}`
              }
              classes="bg-black text-white rounded-full px-2 py-1"
            />

            <IconButton
              icon={<Icons.report />}
              text="Report Issue"
              classes="bg-transparent border border-error 
              text-error rounded-full px-2 py-1"
            />

            <Divider classes="w-px h-full bg-gray30" />

            <IconButton icon={<Icons.edit />} classes="" />

            <Divider classes="w-px h-full bg-gray30" />

            <IconButton icon={<Icons.share />} classes="" />
          </div>
          <div className="w-full mt-6">
            <ImagesBlock images={card.imageLinks} />
          </div>
        </div>
      </div>
    </article>
  );
};

export default TripLong;
